### ISSUE TITLE
Minor go language warning at every run

### ISSUE THREAD

**Issue by scruss** [kevin-cantwell/dotmatrix#2]
Doesn't affect image conversion, but I get

```
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

at the end of every run.

**Comment by kevin-cantwell** [comment]
Thanks. Seems like I'm using `github.com/codegangsta/cli` in an outdated way.

**Comment by kevin-cantwell** [comment]
Actually I am vendoring an older version of the cli package. I moved it out of `Godeps/_workspace/src` and into the now-standard vendor dir. This _should_ resolve the issue.
